### ISSUE TITLE
Comment out final "exercise" cell in NB on Large Scale Structure

### ISSUE THREAD

**Issue by rnikutta** [astro-datalab/notebooks-latest#131]
Hi @DavidVargasMora and @stephjuneau 

The noteboook 06_EPO/TeenAstronomyCafe/07_Large_Scale_Structure_of_the_Universe/Large_Scale_Structure_of_the_Universe.ipynb currently fails our auto tests because the final cell, which is meant as an exercise to the students, contains invalid Python.

Can you please either fix the syntactically incorrect Python, or comment out the entire cell, with a pre-note to the reader what to do?

All NBs must be able to run through without interaction, and without errors.
Thanks!

**Comment by stephjuneau** [comment]
This was resolved.
