### ISSUE TITLE
Exploring SMASH DR2 - ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by JosephKarpinski** [astro-datalab/notebooks-latest#151]
Exploring SMASH DR2 receiving multiple errors.

https://github.com/astro-datalab/notebooks-latest/blob/master/03_ScienceExamples/GalacticStructure/ExploringSMASHDR2.ipynb

See attached screen prints

<img width="1358" alt="Screen Shot 2023-01-26 at 1 54 29 PM" src="https://user-images.githubusercontent.com/37123616/214924860-ec6d8236-a2b8-4315-a03b-4682ee48230c.png">

<img width="1358" alt="Screen Shot 2023-01-26 at 1 54 59 PM" src="https://user-images.githubusercontent.com/37123616/214924895-31b43b7d-cb5f-459e-8c48-e781e9e6ee4d.png">

<img width="1358" alt="Screen Shot 2023-01-26 at 1 55 16 PM" src="https://user-images.githubusercontent.com/37123616/214924940-daf27051-151b-462a-8e9c-8388540d3615.png">

**Comment by jacquesalice** [comment]
Hi @JosephKarpinski, thanks for reporting this. While I was able to run this notebook without issue, I see that there is a deprecation warning for setting an array element with a sequence for the `rot` variable:

> DeprecationWarning: setting an array element with a sequence. This was supported in some cases where the elements are arrays with a single element. For example `np.array([1, np.array([2])], dtype=int)`. In the future this will raise the same ValueError as `np.array([1, [2]], dtype=int)`.
rot = np.array(rot,np.float64).flatten()

Try replacing `rot=(f4['ra'],f4['dec'],0)` with `rot=(f4['ra'].array[0],f4['dec'].array[0],0)`

Let me know if this works for you, and I will update the notebook accordingly.

**Comment by JosephKarpinski** [comment]
That worked.
Thank you!

<img width="1684" alt="Screen Shot 2023-01-29 at 9 10 18 AM" src="https://user-images.githubusercontent.com/37123616/215332509-02bcb0e0-b669-4703-a7b0-5c8f32f438c8.png">

<img width="1684" alt="Screen Shot 2023-01-29 at 9 11 05 AM" src="https://user-images.githubusercontent.com/37123616/215332522-49bab073-d33a-4ade-8b60-a975627f83ed.png">


<img width="1684" alt="Screen Shot 2023-01-29 at 9 11 40 AM" src="https://user-images.githubusercontent.com/37123616/215332552-7fd087c3-2746-4482-9b40-fd88bd2ce330.png">
