### ISSUE TITLE
DataLabNotebookTemplate.ipynb has typo, incomplete in dataset cell

### ISSUE THREAD

**Issue by knutago** [astro-datalab/notebooks-latest#7]
The Available Datasets cell in the Notebook Template has the following:
\# these schemas are not astronomical datasets
_remove = set(['ivao','ivao_smash','tap_schema','schema'])

ivao is a typo, should be ivoa.  And the complete list of ivoa tables is larger.  Can we not use a regular expression here?

**Comment by stephjuneau** [comment]
Above is still a problem. Also, the url in top cell for keywords is wrong. It should be the following instead:  https://github.com/astro-datalab/notebooks-latest/blob/master/keywords.txt

**Comment by rnikutta** [comment]
Closing as done. The issues have been fixed sometime.
